"use client";

import { useEffect, useState } from "react";
import { motion, useSpring, useMotionValue } from "framer-motion";

export default function CustomCursor() {
  const [isVisible, setIsVisible] = useState(false);
  const [isHovering, setIsHovering] = useState(false);
  const [isTouchDevice, setIsTouchDevice] = useState(false);

  // Motion values for smooth springing
  const cursorX = useMotionValue(-100);
  const cursorY = useMotionValue(-100);
  
  // Spring configuration for that fluid, responsive feel
  const springConfig = { damping: 25, stiffness: 400, mass: 0.5 };
  const cursorXSpring = useSpring(cursorX, springConfig);
  const cursorYSpring = useSpring(cursorY, springConfig);

  useEffect(() => {
    const isTouch = window.matchMedia("(hover: none), (pointer: coarse)").matches;
    setIsTouchDevice(isTouch);
    
    if (isTouch) return;

    const moveCursor = (e: MouseEvent) => {
      // Ignore synthetic mouse events generated by touch taps
      if ((e as any).sourceCapabilities && (e as any).sourceCapabilities.firesTouchEvents) {
        setIsVisible(false);
        return;
      }
      
      cursorX.set(e.clientX);
      cursorY.set(e.clientY);
      
      if (!isVisible) setIsVisible(true);
    };

    const handleMouseLeave = () => {
      setIsVisible(false);
      setIsHovering(false);
    };

    const handleTouchStart = () => {
      setIsVisible(false);
      setIsHovering(false);
    };

    window.addEventListener("mousemove", moveCursor);
    document.addEventListener("mouseleave", handleMouseLeave);
    window.addEventListener("touchstart", handleTouchStart, { passive: true });
    window.addEventListener("touchmove", handleTouchStart, { passive: true });

    return () => {
      window.removeEventListener("mousemove", moveCursor);
      document.removeEventListener("mouseleave", handleMouseLeave);
      window.removeEventListener("touchstart", handleTouchStart);
      window.removeEventListener("touchmove", handleTouchStart);
    };
  }, [cursorX, cursorY, isVisible]);

  useEffect(() => {
    if (isTouchDevice) return;

    const interactiveSelectors = 'a, button, input, select, textarea, .event-card, .faq-question, .filter-chip, .event-tag-chip, .timeline-tab, .brochure-action-btn, .resource-btn, .operator-card, .cmd-badge';

    const handleMouseOver = (e: MouseEvent) => {
      if (e.target && (e.target as Element).closest && (e.target as Element).closest(interactiveSelectors)) {
        setIsHovering(true);
      }
    };

    const handleMouseOut = (e: MouseEvent) => {
      if (e.target && (e.target as Element).closest && (e.target as Element).closest(interactiveSelectors)) {
        setIsHovering(false);
      }
    };

    document.addEventListener("mouseover", handleMouseOver);
    document.addEventListener("mouseout", handleMouseOut);

    return () => {
      document.removeEventListener("mouseover", handleMouseOver);
      document.removeEventListener("mouseout", handleMouseOut);
    };
  }, [isTouchDevice]);

  if (isTouchDevice) return null;

  return (
    <motion.div
      className="fixed top-0 left-0 w-8 h-8 -ml-4 -mt-4 border border-[var(--cyan-accent)] rounded-full pointer-events-none z-[9999] mix-blend-screen flex items-center justify-center transition-all duration-200 ease-out"
      style={{
        x: cursorXSpring,
        y: cursorYSpring,
        opacity: isVisible ? 1 : 0,
        backgroundColor: isHovering ? "rgba(0, 243, 255, 0.1)" : "transparent",
        scale: isHovering ? 1.5 : 1,
        boxShadow: isHovering ? "0 0 15px rgba(0, 243, 255, 0.4), inset 0 0 10px rgba(0, 243, 255, 0.2)" : "0 0 8px rgba(0, 243, 255, 0.2)",
      }}
    >
      <div 
        className="w-[3px] h-[3px] bg-[var(--cyan-accent)] rounded-full transition-transform duration-200"
        style={{ transform: isHovering ? 'scale(0)' : 'scale(1)' }}
      />
    </motion.div>
  );
}
